name: Delete old packages

on:
  workflow_call:
    secrets:
      gha-pkg-token:
        description: "Personal access token with delete:packages permission"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Extract package name
        id: extract_package_name
        run: |
          package_name=`echo ${{ env.IMAGE_NAME }} | sed "s/^.*vg-\(.*\)/\1/"`
          echo "Set package_name to ${package_name}"
          echo "::set-output name=package_name::${package_name}"

      - name: Delete old packages
        uses: actions/delete-package-versions@v3
        with:
          token: ${{ secrets.gha-pkg-token }}
          package-name: ${{ steps.extract_package_name.outputs.package_name }}
          min-versions-to-keep: 10
          ignore-versions: ":latest"
