name: Create new release for docker repo

on:
  workflow_call:
    inputs:
      build-args:
        description: "List of build-time variables (https://github.com/docker/build-push-action#inputs)"
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-new-release:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.version-info.outputs.new_tag }}
      new_version: ${{ steps.version-info.outputs.new_version }}
      release_type: ${{ steps.version-info.outputs.release_type }}
      changelog: ${{ steps.version-info.outputs.changelog }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get new version information
        id: version-info
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          dry_run: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            --build-arg VERSION="${{ steps.version-info.outputs.new_version }}"
            ${{ inputs.build-args }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version-info.outputs.new_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version-info.outputs.new_tag }}
          release_name: Release ${{ steps.version-info.outputs.new_tag }}
          body: ${{ steps.version-info.outputs.changelog }}
