name: Create new release for docker repo

on:
  workflow_call:
    inputs:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-new-version-info:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.version-info.outputs.new_tag }}
      new_version: ${{ steps.version-info.outputs.new_version }}
      release_type: ${{ steps.version-info.outputs.release_type }}
      changelog: ${{ steps.version-info.outputs.changelog }}

    steps:
      - uses: actions/checkout@v3

      - name: Get new version information
        id: version-info
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          dry_run: true

  build-and-push-new-package:
    runs-on: ubuntu-latest
    needs: create-new-version-info
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.create-new-version-info.outputs.new_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  create-new-release:
    runs-on: ubuntu-latest
    needs: [create-new-version-info, build-and-push-new-package]

    steps:
      - uses: actions/checkout@v3

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create-new-version-info.outputs.new_tag }}
          release_name: Release ${{ needs.create-new-version-info.outputs.new_tag }}
          body: ${{ needs.create-new-version-info.outputs.changelog }}
